### ISSUE TITLE
The featured images are not displayed in the posts. 

### ISSUE THREAD

**Issue by blissfulStar** [te2dy/marianne#13]
Instead it just clicks to the next page as a link.  Please advise.

**Comment by blissfulStar** [comment]
And there is no editing of default images of posts.

**Comment by te2dy** [comment]
Could you provide a link to your site so I can take a look?

On WP support forum, you’ve also said that featured images were not displayed in their actual size. Is the option "Expand featured images that are not wide enough" unchecked in Appearance > Customize > Global Settings?

**Comment by blissfulStar** [comment]
That was some else that had an issue with actual size.  I'm not there yet, I'm just trying to get the images displayed on the featured post at http://www.theluckytradingpost.com/wordpress

**Comment by blissfulStar** [comment]
I figured it out. Thank you and I love your simple theme.
