### ISSUE TITLE
Add Mastodon support for Social Links

### ISSUE THREAD

**Issue by ankitrgadiya** [te2dy/marianne#15]
[Mastodon](http://joinmastodon.org) is the federated social media platform compatible with various other federated platforms. Is it possible to add support for Mastodon Icon in Social Links?

An inconvenience is that Feather icons doesn't already have a Mastodon Icon and they won't add it either in the near future (https://github.com/feathericons/feather/issues/273). As per their deprecation thread, Simple Icons is a possible alternative.

https://simpleicons.org/?q=mastodon

**Comment by te2dy** [comment]
Thank you for your suggestion! I'll see about replacing all the current icons with these.

You will find Mastodon icon in the next release (today).
