### ISSUE TITLE
current versions of mailpoet3 need newer jquery version

### ISSUE THREAD

**Issue by himpierre** [te2dy/marianne#21]
hello devs.

thanks for providing this amazing theme. i have a problem though with mailpoet3 newer than 3.60.4. according to the devs there the jquery version of this theme is to old. is there something you can do about it?

for reference: https://wordpress.org/support/topic/mailpoet-3-module-form-and-an-error-has-happened-while-performing-a-request/

cheers, t.

**Comment by te2dy** [comment]
Hey ! 👋🏻

Marianne calls the jQuery version of your WordPress installation; it doesn't load its own one. This is a theme requirement that I have to respect in order for this theme to be published in the WordPress Theme Directory.

> WordPress includes a number of libraries such as jQuery. For security and stability reasons, themes may not include those libraries in their own code. Instead, themes must use the versions of those libraries packaged with WordPress. ([link](https://make.wordpress.org/themes/handbook/review/required/))

Maybe a plugin could solve your problem. 🤷🏻‍♂️

**Comment by himpierre** [comment]
Thanks for your answer!

Am 2. November 2021 08:11:37 MEZ schrieb te2dy ***@***.***>:
